FROM python:3.13-alpine

WORKDIR /app

COPY ./pyproject.toml .
RUN apk add --no-cache git
# Install Node.js and npm
RUN apk add --no-cache nodejs npm
# Install Python packages
RUN pip install --no-cache-dir .

WORKDIR /app

COPY . .

EXPOSE 5000
EXPOSE 5173

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]