FROM python:3.13-alpine

WORKDIR /app

COPY ./pyproject.toml .
RUN apk add --no-cache git
# Install Node.js and npm
RUN apk add --no-cache nodejs npm
# Install Python packages
RUN pip install .[dev] --no-cache-dir .
# Install NPM packages
COPY ./ui/package.json ./ui/package-lock.json ./ui/
WORKDIR /app/ui
RUN npm ci

WORKDIR /app
# node_modules folder is ignored, so it shouldn't affect node_modules in the container.
COPY . .

ENV ENV=dev
EXPOSE 5000
EXPOSE 5173
ARG playlistPath=./playlist.json
ENV PLAYLIST_PATH=$playlistPath
CMD ["python", "main.py", "--port", "5000", "--host", "0.0.0.0", "-pp", "$PLAYLIST_PATH"]